apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fs-pvc-restore
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: fs-pv-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
