apiVersion: v1
kind: Pod
metadata:
  namespace: mysql-ajinkya
  name: ajinkya-app
  labels:
    app: ajinkya-app
    tier: mysql
spec:
  containers:
  - image: mysql:5.6
    name: mysql-container
    env:
      - name: MYSQL_ALLOW_EMPTY_PASSWORD
        value: "yes"
    ports:
      - containerPort: 3306
        name: mysql
    volumeMounts:
    - name: mysql-pv
      mountPath: /var/lib/mysql
  volumes:
  - name: mysql-pv
    persistentVolumeClaim:
      claimName: ajinkya-mysql-pvc