apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ajinkya-app
    tier: mysql
  name: ajinkya-mysql-pvc
  namespace: mysql-ajinkya
spec:
  storageClassName: standard-rwo
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
