apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-app.fullname" . }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app1.service.type }}
  ports:
    {{- .Values.app1.service.ports | toYaml | nindent 4 }}
  selector:
    {{- include "web-app.selectorLabels" . | nindent 4 }}
