apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sample-nginx
    data: scratch
  name: sample-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: sample-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /test-pd 
          name: nginx-volume
      volumes: 
        - name: nginx-volume
          persistentVolumeClaim:
            claimName: csi-pvc
