apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: k8s-demo-app
    tier: mysql
  name: tvk-mysql-pvc
  namespace: mysql-demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard-rwo